### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ademibowale**
## In this Milestone Project

- I create a new game with the name of my choice by using the API.
- I Implement the "Refresh" button (receiving data from the API and parsing the JSON).
- I Implement the form "Submit" button (sending data to the API).
- I Use arrow functions instead of the function keyword.
- I Use async and await JavaScript features to consume the API.

### CODE REVIEW

**Review by Mre55 — CHANGES_REQUESTED** [review]
**Hi @ademibowale,**

Great work on making the changes requested by a previously 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

 ## Required Changes ♻️

- [x] Let me clear what I said early as described in [this blog](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md#opening-pull-requests) on `Opening pull requests` the `dev` branch has to be created from `main` branch as you have now and make sure `dev` branch is default branch then create new branch from `dev` branch (since you have `leader_board-1`) create pull request from `leader_board-1` to `dev` branch and submit that pull request. I hope this is more clear. If not read [this file](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md#opening-pull-requests) `Opening pull requests` again.

_Check the comments under the review._



## Optional suggestions 🟡 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ademibowale** [comment]
## In this Milestone...

## Leader App

- [ ] I work on the Leaderboard list app, sending and receiving data from/to the Leaderboard API.
- [ ] Create a new game with the name of your choice by using the API.
     - I saved the ID of my game that will be returned by API.
- [ ]  I implement the "Refresh" button that will get all scores for a game created by me from the API (receiving data from the API and parsing the JSON)..
- [ ] Make JavaScript code asynchronous.
- [ ] Implement the form "Submit" button that will save a score for a game created by you (sending data to the API).
- [ ] i use arrow functions instead of the function keyword.
- [ ] I Use async and await JavaScript features to consume the API.

**Review by ishimwezachee — APPROVED** [review]
Hi @ademibowale , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
The PR title and description are professional and descriptive ✅
The commit messages are meaningful ✅
The README is well documented ✅
Linters are working properly ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ademibowale** [comment]
@Mre55 all required changes have been made thank you for your contribution .

**Comment by ademibowale** [comment]
@ishimwezachee thank you so much

**Pull request merged**
